## Apriori Frequent Pattern Mining

In [27]:
# Importing required libraries
import pandas as pd
import numpy as np
from itertools import combinations
import time

In [28]:
# Reading data file
adult = pd.read_excel('adult.xlsx')
adult.head()

,Age,Workclass,fnlwgt,Education,Edunum,Marital,Occupation,Relationship,Race,Sex,Gain,Loss,Hoursperweek,Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [29]:
# Removing irrelevant columns
adult.drop(['fnlwgt', 'Edunum'], axis = 1, inplace = True)
adult.head()

,Age,Workclass,Education,Marital,Occupation,Relationship,Race,Sex,Gain,Loss,Hoursperweek,Country,Income
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [30]:
# Size of original data
adult.shape

(32561, 13)

In [31]:
# Removing missing values from data
adult.replace(' ?', np.NaN, inplace = True)
adult.dropna(axis = 0, inplace = True)

# Size of data after removing missing values
adult.shape

(30162, 13)

In [32]:
# Converting numeric data to categorical data
adult['Age'] = pd.cut(adult['Age'], [0, 25, 40, np.inf], labels=["young", "middle_aged", "old"])
adult['Gain'] = pd.cut(adult['Gain'], [-1, 1, np.inf], labels=["No_Gain", "Gain"])
adult['Loss'] = pd.cut(adult['Loss'], [-1, 1, np.inf], labels=["No_Loss", "Loss"])
adult['Hoursperweek'] = pd.cut(adult['Hoursperweek'], [-1, 5, 20, 60, np.inf], labels=["Less", "Medium", "Reasonable", "High"])
adult.head()

,Age,Workclass,Education,Marital,Occupation,Relationship,Race,Sex,Gain,Loss,Hoursperweek,Country,Income
0,middle_aged,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,Gain,No_Loss,Reasonable,United-States,<=50K
1,old,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,No_Gain,No_Loss,Medium,United-States,<=50K
2,middle_aged,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,No_Gain,No_Loss,Reasonable,United-States,<=50K
3,old,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,No_Gain,No_Loss,Reasonable,United-States,<=50K
4,middle_aged,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,No_Gain,No_Loss,Reasonable,Cuba,<=50K

In [33]:
# Generating Candidate 1
def C1(data):
    candidates = {} # empty dictionary to store each item as key and its count as value
    for i in data.index:
        for j in data.loc[i]:
            if (j in candidates): 
                candidates[j] += 1
            else: 
                candidates[j] = 1
    print("\nC1: \n", candidates)
    return candidates

In [34]:
# Generating L1
def L1(c, support):
    l1 = {} # dictionary to store all the items having support more than or equal to minimum support
    l1 = dict((k,v) for k, v in c.items() if v >= support)
    print("\n\nL1: \n", l1)
    return l1

In [35]:
# Function to check if candidate itemset contains infrequent subset
def has_infrequent_subset(candidate, freq, prevL):
    for i in list(combinations(candidate,freq-1)):
        if i not in prevL:
            return True
        return False

In [36]:
# Generating Candidate k
def Ck(k, prevL, df):
    
    # Join
    # For C2:
    if k == 2:
        c = list()
        for key,v in prevL.items():
            if key not in c:
                c.append(key)
            
    # When k is greater than 2, L (k-1) contains list of tuples
    if k > 2:
        c = list()
        for key,v in prevL.items():
            for item in key:
                if item not in c:
                    c.append(item)
                    
    candidates = {} # To store all the candidate items along with its count
    cand = list(combinations(c, k))
    
    # Prune
    for cd in cand:
        if (has_infrequent_subset(cd, k, prevL) == True):
            cand.remove(cd)
            
    for i in cand:
        candidates[i] = 0
    for ind in df.index:
        for i in candidates:
            if set(i).issubset(df.loc[ind]):
                candidates[i] +=1
                
    print("\n\nC", k, ":\n", candidates)
    return candidates

In [37]:
# Generating Lk
def Lk(k, ck, support):
    lk = {}
    # lk contains all the values having support more than minimum support threshold
    lk = dict((key,v) for key, v in ck.items() if v >= support)
    print("\n\nL", k, ":\n", lk)
    return lk

In [38]:
# Function for Apriori Algorithm
def apriori(data, support):
    
    t1 = time.time()
    s = int((support/100)*len(data))
    print("Minimum support = ", s)
    
    lk = {}
    candidateK = {}
    candidateK = C1(data)
    lk = L1(candidateK, s)
    
    k = 2
    while lk != {}:
        candidateK = Ck(k, lk, data)
        lk = Lk(k, candidateK, s)
        k += 1
    t2 = time.time()
    
    exec_time = t2 - t1
    
    print("\nTotal execution time = ", exec_time)

    return

In [41]:
apriori(adult, 30)

Minimum support =  12064

C1:
 {'middle_aged': 12092, ' State-gov': 1279, ' Bachelors': 5044, ' Never-married': 9726, ' Adm-clerical': 3721, ' Not-in-family': 7726, ' White': 25933, ' Male': 20380, 'Gain': 2538, 'No_Loss': 28735, 'Reasonable': 26722, ' United-States': 27504, ' <=50K': 22654, 'old': 12402, ' Self-emp-not-inc': 2499, ' Married-civ-spouse': 14065, ' Exec-managerial': 3992, ' Husband': 12463, 'No_Gain': 27624, 'Medium': 2277, ' Private': 22286, ' HS-grad': 9840, ' Divorced': 4214, ' Handlers-cleaners': 1350, ' 11th': 1048, ' Black': 2817, ' Prof-specialty': 4038, ' Wife': 1406, ' Female': 9782, ' Cuba': 92, ' Masters': 1627, ' 9th': 455, ' Married-spouse-absent': 370, ' Other-service': 3212, ' Jamaica': 80, ' >50K': 7508, ' Some-college': 6678, 'High': 1052, ' Asian-Pac-Islander': 895, ' India': 100, 'young': 5668, ' Own-child': 4466, ' Assoc-acdm': 1008, ' Sales': 3584, ' 7th-8th': 557, ' Transport-moving': 1572, ' Amer-Indian-Eskimo': 286, ' Mexico': 610, ' Farming-fishing': 989, ' Machine-op-inspct': 1966, ' Unmarried': 3212, ' Doctorate': 375, ' Separated': 939, ' Federal-gov': 943, 'Loss': 1427, ' Tech-support': 912, ' Local-gov': 2067, ' Craft-repair': 4030, ' Protective-serv': 644, ' Puerto-Rico': 109, ' Married-AF-spouse': 21, ' Assoc-voc': 1307, ' Other': 231, ' Prof-school': 542, ' Honduras': 12, ' Self-emp-inc': 1074, ' 5th-6th': 288, ' Other-relative': 889, ' England': 86, ' Canada': 107, ' Germany': 128, ' Iran': 42, ' Widowed': 827, ' Philippines': 188, 'Less': 111, ' Poland': 56, ' 10th': 820, ' Preschool': 45, ' Columbia': 56, ' Cambodia': 18, ' Thailand': 17, ' Ecuador': 27, ' Laos': 17, ' Taiwan': 42, ' Haiti': 42, ' Portugal': 34, ' 12th': 377, ' 1st-4th': 151, ' Dominican-Republic': 67, ' Armed-Forces': 9, ' El-Salvador': 100, ' France': 27, ' Priv-house-serv': 143, ' Guatemala': 63, ' Italy': 68, ' China': 68, ' South': 71, ' Japan': 59, ' Yugoslavia': 16, ' Peru': 30, ' Outlying-US(Guam-USVI-etc)': 14, ' Scotland': 11, ' Trinadad&Tobago': 18, ' Greece': 29, ' Without-pay': 14, ' Nicaragua': 33, ' Vietnam': 64, ' Hong': 19, ' Ireland': 24, ' Hungary': 13, ' Holand-Netherlands': 1}


L1:
 {'middle_aged': 12092, ' White': 25933, ' Male': 20380, 'No_Loss': 28735, 'Reasonable': 26722, ' United-States': 27504, ' <=50K': 22654, 'old': 12402, ' Married-civ-spouse': 14065, ' Husband': 12463, 'No_Gain': 27624, ' Private': 22286}


C 2 :
 {('middle_aged', ' Male'): 8373, ('middle_aged', 'Reasonable'): 11181, ('middle_aged', ' <=50K'): 9205, ('middle_aged', ' Married-civ-spouse'): 5869, ('middle_aged', 'No_Gain'): 11138, (' White', ' Male'): 18038, (' White', 'Reasonable'): 22922, (' White', ' <=50K'): 19094, (' White', ' Married-civ-spouse'): 12656, (' White', 'No_Gain'): 23668, (' Male', 'No_Loss'): 19290, (' Male', ' United-States'): 18572, (' Male', 'old'): 8785, (' Male', ' Husband'): 12462, (' Male', ' Private'): 14644, ('No_Loss', ' United-States'): 26175, ('No_Loss', 'old'): 11656, ('No_Loss', ' Husband'): 11645, ('No_Loss', ' Private'): 21326, ('Reasonable', ' <=50K'): 19758, ('Reasonable', ' Married-civ-spouse'): 12871, ('Reasonable', 'No_Gain'): 24419, (' United-States', ' <=50K'): 20509, (' United-States', ' Married-civ-spouse'): 12798, (' United-States', 'No_Gain'): 25145, (' <=50K', 'old'): 7892, (' <=50K', ' Husband'): 6784, (' <=50K', ' Private'): 17410, ('old', ' Husband'): 6899, ('old', ' Private'): 7965, (' Married-civ-spouse', 'No_Gain'): 12356, (' Husband', 'No_Gain'): 10950, ('No_Gain', ' Private'): 20583}


L 2 :
 {(' White', ' Male'): 18038, (' White', 'Reasonable'): 22922, (' White', ' <=50K'): 19094, (' White', ' Married-civ-spouse'): 12656, (' White', 'No_Gain'): 23668, (' Male', 'No_Loss'): 19290, (' Male', ' United-States'): 18572, (' Male', ' Husband'): 12462, (' Male', ' Private'): 14644, ('No_Loss', ' United-States'): 26175, ('No_Loss', ' Private'): 21326, ('Reasonable', ' <=50K'): 19758, ('Reasonable', ' Married-civ-spouse'): 12871, ('Reasonable', 'No_Gain'): 24419, (' United-States', ' <=50K'): 20509, (' United-States', ' Married-civ-spouse'): 12798, (' United-States', 'No_Gain'): 25145, (' <=50K', ' Private'): 17410, (' Married-civ-spouse', 'No_Gain'): 12356, ('No_Gain', ' Private'): 20583}


C 3 :
 {(' White', ' Male', 'Reasonable'): 16249, (' White', ' Male', ' <=50K'): 12170, (' White', ' Male', ' Married-civ-spouse'): 11416, (' White', ' Male', 'No_Gain'): 16242, (' White', ' Male', 'No_Loss'): 17049, (' White', ' Male', ' United-States'): 16848, (' White', ' Male', ' Husband'): 11322, (' White', ' Male', ' Private'): 12924, (' White', 'Reasonable', ' <=50K'): 16586, (' White', 'Reasonable', ' Married-civ-spouse'): 11570, (' White', 'Reasonable', 'No_Gain'): 20869, (' White', 'Reasonable', 'No_Loss'): 21778, (' White', 'Reasonable', ' United-States'): 21369, (' White', 'Reasonable', ' Husband'): 10407, (' White', 'Reasonable', ' Private'): 17095, (' White', ' <=50K', ' Married-civ-spouse'): 6797, (' White', ' <=50K', 'No_Gain'): 18275, (' White', ' <=50K', 'No_Loss'): 18489, (' White', ' <=50K', ' United-States'): 17679, (' White', ' <=50K', ' Husband'): 6097, (' White', ' <=50K', ' Private'): 14670, (' White', ' Married-civ-spouse', 'No_Gain'): 11092, (' White', ' Married-civ-spouse', 'No_Loss'): 11822, (' White', ' Married-civ-spouse', ' United-States'): 11854, (' White', ' Married-civ-spouse', ' Husband'): 11314, (' White', ' Married-civ-spouse', ' Private'): 8560, (' White', 'No_Gain', 'No_Loss'): 22386, (' White', 'No_Gain', ' United-States'): 22068, (' White', 'No_Gain', ' Husband'): 9928, (' White', 'No_Gain', ' Private'): 17619, (' White', 'No_Loss', ' Husband'): 10572, (' White', ' United-States', ' Husband'): 10641, (' White', ' Husband', ' Private'): 7628, (' Male', 'Reasonable', ' Married-civ-spouse'): 11577, (' Male', 'Reasonable', 'No_Loss'): 17377, (' Male', 'Reasonable', ' Husband'): 11464, (' Male', ' <=50K', ' Married-civ-spouse'): 6886, (' Male', ' <=50K', 'No_Loss'): 13535, (' Male', ' <=50K', ' Husband'): 6783, (' Male', ' Married-civ-spouse', 'No_Gain'): 11061, (' Male', ' Married-civ-spouse', ' United-States'): 11498, (' Male', ' Married-civ-spouse', ' Private'): 8506, (' Male', 'No_Gain', ' United-States'): 16738, (' Male', 'No_Gain', ' Private'): 13328, (' Male', 'No_Loss', ' United-States'): 17562, (' Male', 'No_Loss', ' Husband'): 11644, (' Male', 'No_Loss', ' Private'): 13925, (' Male', ' United-States', ' Husband'): 11414, (' Male', ' United-States', ' Private'): 13209, (' Male', ' Husband', ' Private'): 8410, ('Reasonable', ' <=50K', ' Married-civ-spouse'): 6931, ('Reasonable', ' <=50K', 'No_Gain'): 18936, ('Reasonable', ' <=50K', 'No_Loss'): 19151, ('Reasonable', ' <=50K', ' United-States'): 17835, ('Reasonable', ' <=50K', ' Husband'): 6171, ('Reasonable', ' <=50K', ' Private'): 15336, ('Reasonable', ' Married-civ-spouse', 'No_Gain'): 11314, ('Reasonable', ' Married-civ-spouse', 'No_Loss'): 12045, ('Reasonable', ' Married-civ-spouse', ' United-States'): 11707, ('Reasonable', ' Married-civ-spouse', ' Husband'): 11458, ('Reasonable', ' Married-civ-spouse', ' Private'): 8939, ('Reasonable', 'No_Gain', 'No_Loss'): 23141, ('Reasonable', 'No_Gain', ' United-States'): 22184, ('Reasonable', 'No_Gain', ' Husband'): 10089, ('Reasonable', 'No_Gain', ' Private'): 18367, ('Reasonable', 'No_Loss', ' Husband'): 10714, ('Reasonable', ' United-States', ' Husband'): 10497, ('Reasonable', ' Husband', ' Private'): 7921, (' <=50K', ' Married-civ-spouse', 'No_Loss'): 7409, (' <=50K', ' Married-civ-spouse', ' Husband'): 6779, (' <=50K', 'No_Gain', 'No_Loss'): 21021, (' <=50K', 'No_Gain', ' Husband'): 6411, (' <=50K', 'No_Loss', ' United-States'): 19869, (' <=50K', 'No_Loss', ' Private'): 16914, (' <=50K', ' United-States', ' Private'): 15594, (' Married-civ-spouse', 'No_Gain', 'No_Loss'): 11448, (' Married-civ-spouse', 'No_Gain', ' United-States'): 11214, (' Married-civ-spouse', 'No_Gain', ' Husband'): 10942, (' Married-civ-spouse', 'No_Gain', ' Private'): 8437, (' Married-civ-spouse', 'No_Loss', ' Husband'): 11636, (' Married-civ-spouse', ' United-States', ' Husband'): 11406, (' Married-civ-spouse', ' Husband', ' Private'): 8405, ('No_Gain', 'No_Loss', ' Husband'): 10132, ('No_Gain', ' United-States', ' Husband'): 10013, ('No_Gain', ' Husband', ' Private'): 7436, ('No_Loss', ' United-States', ' Husband'): 10658, ('No_Loss', ' United-States', ' Private'): 19237, (' United-States', ' Husband', ' Private'): 7627}


L 3 :
 {(' White', ' Male', 'Reasonable'): 16249, (' White', ' Male', ' <=50K'): 12170, (' White', ' Male', 'No_Gain'): 16242, (' White', ' Male', 'No_Loss'): 17049, (' White', ' Male', ' United-States'): 16848, (' White', ' Male', ' Private'): 12924, (' White', 'Reasonable', ' <=50K'): 16586, (' White', 'Reasonable', 'No_Gain'): 20869, (' White', 'Reasonable', 'No_Loss'): 21778, (' White', 'Reasonable', ' United-States'): 21369, (' White', 'Reasonable', ' Private'): 17095, (' White', ' <=50K', 'No_Gain'): 18275, (' White', ' <=50K', 'No_Loss'): 18489, (' White', ' <=50K', ' United-States'): 17679, (' White', ' <=50K', ' Private'): 14670, (' White', 'No_Gain', 'No_Loss'): 22386, (' White', 'No_Gain', ' United-States'): 22068, (' White', 'No_Gain', ' Private'): 17619, (' Male', 'Reasonable', 'No_Loss'): 17377, (' Male', ' <=50K', 'No_Loss'): 13535, (' Male', 'No_Gain', ' United-States'): 16738, (' Male', 'No_Gain', ' Private'): 13328, (' Male', 'No_Loss', ' United-States'): 17562, (' Male', 'No_Loss', ' Private'): 13925, (' Male', ' United-States', ' Private'): 13209, ('Reasonable', ' <=50K', 'No_Gain'): 18936, ('Reasonable', ' <=50K', 'No_Loss'): 19151, ('Reasonable', ' <=50K', ' United-States'): 17835, ('Reasonable', ' <=50K', ' Private'): 15336, ('Reasonable', 'No_Gain', 'No_Loss'): 23141, ('Reasonable', 'No_Gain', ' United-States'): 22184, ('Reasonable', 'No_Gain', ' Private'): 18367, (' <=50K', 'No_Gain', 'No_Loss'): 21021, (' <=50K', 'No_Loss', ' United-States'): 19869, (' <=50K', 'No_Loss', ' Private'): 16914, (' <=50K', ' United-States', ' Private'): 15594, ('No_Loss', ' United-States', ' Private'): 19237}

C 4 :
 {(' White', ' Male', 'Reasonable', ' <=50K'): 10786, (' White', ' Male', 'Reasonable', 'No_Gain'): 14612, (' White', ' Male', 'Reasonable', 'No_Loss'): 15352, (' White', ' Male', 'Reasonable', ' United-States'): 15155, (' White', ' Male', 'Reasonable', ' Private'): 11827, (' White', ' Male', ' <=50K', 'No_Gain'): 11598, (' White', ' Male', ' <=50K', 'No_Loss'): 11769, (' White', ' Male', ' <=50K', ' United-States'): 11229, (' White', ' Male', ' <=50K', ' Private'): 9092, (' White', ' Male', 'No_Gain', 'No_Loss'): 15253, (' White', ' Male', 'No_Gain', ' United-States'): 15140, (' White', ' Male', 'No_Gain', ' Private'): 11730, (' White', ' Male', 'No_Loss', ' United-States'): 15898, (' White', ' Male', 'No_Loss', ' Private'): 12270, (' White', ' Male', ' United-States', ' Private'): 11956, (' White', 'Reasonable', ' <=50K', 'No_Gain'): 15873, (' White', 'Reasonable', ' <=50K', 'No_Loss'): 16056, (' White', 'Reasonable', ' <=50K', ' United-States'): 15308, (' White', 'Reasonable', ' <=50K', ' Private'): 12888, (' White', 'Reasonable', 'No_Gain', 'No_Loss'): 19725, (' White', 'Reasonable', 'No_Gain', ' United-States'): 19417, (' White', 'Reasonable', 'No_Gain', ' Private'): 15701, (' White', 'Reasonable', 'No_Loss', ' United-States'): 20267, (' White', 'Reasonable', 'No_Loss', ' Private'): 16314, (' White', 'Reasonable', ' United-States', ' Private'): 15803, (' White', ' <=50K', 'No_Gain', 'No_Loss'): 17670, (' White', ' <=50K', 'No_Gain', ' United-States'): 16922, (' White', ' <=50K', 'No_Gain', ' Private'): 14071, (' White', ' <=50K', 'No_Loss', ' United-States'): 17100, (' White', ' <=50K', 'No_Loss', ' Private'): 14233, (' White', ' <=50K', ' United-States', ' Private'): 13452, (' White', 'No_Gain', 'No_Loss', ' United-States'): 20836, (' White', 'No_Gain', 'No_Loss', ' Private'): 16755, (' White', 'No_Gain', ' United-States', ' Private'): 16292, (' Male', 'Reasonable', ' <=50K', 'No_Gain'): 11853, (' Male', 'Reasonable', ' <=50K', ' United-States'): 11163, (' Male', 'Reasonable', 'No_Gain', 'No_Loss'): 15575, (' Male', 'Reasonable', 'No_Gain', ' Private'): 12174, (' Male', 'Reasonable', 'No_Loss', ' United-States'): 15806, (' Male', 'Reasonable', 'No_Loss', ' Private'): 12732, (' Male', ' <=50K', 'No_Gain', 'No_Loss'): 12898, (' Male', ' <=50K', 'No_Gain', ' Private'): 10028, (' Male', ' <=50K', 'No_Loss', ' United-States'): 12187, (' Male', ' <=50K', 'No_Loss', ' Private'): 10173, (' Male', 'No_Gain', 'No_Loss', ' United-States'): 15728, (' Male', 'No_Gain', ' United-States', ' Private'): 11991, (' Male', 'No_Loss', ' United-States', ' Private'): 12538, ('Reasonable', ' <=50K', 'No_Gain', 'No_Loss'): 18329, ('Reasonable', ' <=50K', 'No_Gain', ' United-States'): 17084, ('Reasonable', ' <=50K', 'No_Gain', ' Private'): 14733, ('Reasonable', ' <=50K', 'No_Loss', ' United-States'): 17273, ('Reasonable', ' <=50K', 'No_Loss', ' Private'): 14891, ('Reasonable', ' <=50K', ' United-States', ' Private'): 13678, ('Reasonable', 'No_Gain', 'No_Loss', ' United-States'): 20994, ('Reasonable', 'No_Gain', 'No_Loss', ' Private'): 17496, ('Reasonable', 'No_Gain', ' United-States', ' Private'): 16510, (' <=50K', 'No_Gain', 'No_Loss', ' United-States'): 19009, (' <=50K', 'No_Gain', 'No_Loss', ' Private'): 16230, (' <=50K', 'No_Loss', ' United-States', ' Private'): 15132}


L 4 :
 {(' White', ' Male', 'Reasonable', 'No_Gain'): 14612, (' White', ' Male', 'Reasonable', 'No_Loss'): 15352, (' White', ' Male', 'Reasonable', ' United-States'): 15155, (' White', ' Male', 'No_Gain', 'No_Loss'): 15253, (' White', ' Male', 'No_Gain', ' United-States'): 15140, (' White', ' Male', 'No_Loss', ' United-States'): 15898, (' White', ' Male', 'No_Loss', ' Private'): 12270, (' White', 'Reasonable', ' <=50K', 'No_Gain'): 15873, (' White', 'Reasonable', ' <=50K', 'No_Loss'): 16056, (' White', 'Reasonable', ' <=50K', ' United-States'): 15308, (' White', 'Reasonable', ' <=50K', ' Private'): 12888, (' White', 'Reasonable', 'No_Gain', 'No_Loss'): 19725, (' White', 'Reasonable', 'No_Gain', ' United-States'): 19417, (' White', 'Reasonable', 'No_Gain', ' Private'): 15701, (' White', 'Reasonable', 'No_Loss', ' United-States'): 20267, (' White', 'Reasonable', 'No_Loss', ' Private'): 16314, (' White', 'Reasonable', ' United-States', ' Private'): 15803, (' White', ' <=50K', 'No_Gain', 'No_Loss'): 17670, (' White', ' <=50K', 'No_Gain', ' United-States'): 16922, (' White', ' <=50K', 'No_Gain', ' Private'): 14071, (' White', ' <=50K', 'No_Loss', ' United-States'): 17100, (' White', ' <=50K', 'No_Loss', ' Private'): 14233, (' White', ' <=50K', ' United-States', ' Private'): 13452, (' White', 'No_Gain', 'No_Loss', ' United-States'): 20836, (' White', 'No_Gain', 'No_Loss', ' Private'): 16755, (' White', 'No_Gain', ' United-States', ' Private'): 16292, (' Male', 'Reasonable', 'No_Gain', 'No_Loss'): 15575, (' Male', 'Reasonable', 'No_Gain', ' Private'): 12174, (' Male', 'Reasonable', 'No_Loss', ' United-States'): 15806, (' Male', 'Reasonable', 'No_Loss', ' Private'): 12732, (' Male', ' <=50K', 'No_Gain', 'No_Loss'): 12898, (' Male', ' <=50K', 'No_Loss', ' United-States'): 12187, (' Male', 'No_Gain', 'No_Loss', ' United-States'): 15728, (' Male', 'No_Loss', ' United-States', ' Private'): 12538, ('Reasonable', ' <=50K', 'No_Gain', 'No_Loss'): 18329, ('Reasonable', ' <=50K', 'No_Gain', ' United-States'): 17084, ('Reasonable', ' <=50K', 'No_Gain', ' Private'): 14733, ('Reasonable', ' <=50K', 'No_Loss', ' United-States'): 17273, ('Reasonable', ' <=50K', 'No_Loss', ' Private'): 14891, ('Reasonable', ' <=50K', ' United-States', ' Private'): 13678, ('Reasonable', 'No_Gain', 'No_Loss', ' United-States'): 20994, ('Reasonable', 'No_Gain', 'No_Loss', ' Private'): 17496, ('Reasonable', 'No_Gain', ' United-States', ' Private'): 16510, (' <=50K', 'No_Gain', 'No_Loss', ' United-States'): 19009, (' <=50K', 'No_Gain', 'No_Loss', ' Private'): 16230, (' <=50K', 'No_Loss', ' United-States', ' Private'): 15132}


C 5 :
 {(' White', ' Male', 'Reasonable', 'No_Gain', 'No_Loss'): 13715, (' White', ' Male', 'Reasonable', 'No_Gain', ' United-States'): 13597, (' White', ' Male', 'Reasonable', 'No_Gain', ' Private'): 10717, (' White', ' Male', 'Reasonable', 'No_Gain', ' <=50K'): 10281, (' White', ' Male', 'Reasonable', 'No_Loss', ' United-States'): 14291, (' White', ' Male', 'Reasonable', 'No_Loss', ' Private'): 11225, (' White', ' Male', 'Reasonable', 'No_Loss', ' <=50K'): 10428, (' White', ' Male', 'Reasonable', ' United-States', ' Private'): 10929, (' White', ' Male', 'Reasonable', ' United-States', ' <=50K'): 9922, (' White', ' Male', 'No_Gain', 'No_Loss', ' United-States'): 14190, (' White', ' Male', 'No_Gain', 'No_Loss', ' Private'): 11076, (' White', ' Male', 'No_Gain', 'No_Loss', ' <=50K'): 11197, (' White', ' Male', 'No_Gain', ' United-States', ' Private'): 10824, (' White', ' Male', 'No_Gain', ' United-States', ' <=50K'): 10699, (' White', ' Male', 'No_Loss', ' United-States', ' Private'): 11325, (' White', ' Male', 'No_Loss', ' United-States', ' <=50K'): 10844, (' White', ' Male', 'No_Loss', ' Private', ' <=50K'): 8807, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States'): 18315, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' Private'): 14920, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' <=50K'): 15343, (' White', 'Reasonable', 'No_Gain', ' United-States', ' Private'): 14483, (' White', 'Reasonable', 'No_Gain', ' United-States', ' <=50K'): 14648, (' White', 'Reasonable', 'No_Gain', ' Private', ' <=50K'): 12358, (' White', 'Reasonable', 'No_Loss', ' United-States', ' Private'): 15049, (' White', 'Reasonable', 'No_Loss', ' United-States', ' <=50K'): 14800, (' White', 'Reasonable', 'No_Loss', ' Private', ' <=50K'): 12498, (' White', 'Reasonable', ' United-States', ' Private', ' <=50K'): 11775, (' White', 'No_Gain', 'No_Loss', ' United-States', ' Private'): 15459, (' White', 'No_Gain', 'No_Loss', ' United-States', ' <=50K'): 16343, (' White', 'No_Gain', 'No_Loss', ' Private', ' <=50K'): 13634, (' White', 'No_Gain', ' United-States', ' Private', ' <=50K'): 12903, (' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States'): 14133, (' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' Private'): 11509, (' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' <=50K'): 11450, (' Male', 'Reasonable', 'No_Gain', ' United-States', ' <=50K'): 10653, (' Male', 'Reasonable', 'No_Gain', ' Private', ' <=50K'): 9049, (' Male', 'Reasonable', 'No_Loss', ' United-States', ' Private'): 11449, (' Male', 'Reasonable', 'No_Loss', ' United-States', ' <=50K'): 10792, (' Male', 'Reasonable', 'No_Loss', ' Private', ' <=50K'): 9175, (' Male', 'No_Gain', 'No_Loss', ' United-States', ' Private'): 11320, (' Male', 'No_Gain', 'No_Loss', ' United-States', ' <=50K'): 11609, (' Male', 'No_Gain', ' United-States', ' Private', ' <=50K'): 8913, (' Male', 'No_Loss', ' United-States', ' Private', ' <=50K'): 9036, ('Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' Private'): 15696, ('Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' <=50K'): 16522, ('Reasonable', 'No_Gain', 'No_Loss', ' Private', ' <=50K'): 14288, ('Reasonable', 'No_Gain', ' United-States', ' Private', ' <=50K'): 13133, ('No_Gain', 'No_Loss', ' United-States', ' Private', ' <=50K'): 14514}


L 5 :
 {(' White', ' Male', 'Reasonable', 'No_Gain', 'No_Loss'): 13715, (' White', ' Male', 'Reasonable', 'No_Gain', ' United-States'): 13597, (' White', ' Male', 'Reasonable', 'No_Loss', ' United-States'): 14291, (' White', ' Male', 'No_Gain', 'No_Loss', ' United-States'): 14190, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States'): 18315, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' Private'): 14920, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' <=50K'): 15343, (' White', 'Reasonable', 'No_Gain', ' United-States', ' Private'): 14483, (' White', 'Reasonable', 'No_Gain', ' United-States', ' <=50K'): 14648, (' White', 'Reasonable', 'No_Gain', ' Private', ' <=50K'): 12358, (' White', 'Reasonable', 'No_Loss', ' United-States', ' Private'): 15049, (' White', 'Reasonable', 'No_Loss', ' United-States', ' <=50K'): 14800, (' White', 'Reasonable', 'No_Loss', ' Private', ' <=50K'): 12498, (' White', 'No_Gain', 'No_Loss', ' United-States', ' Private'): 15459, (' White', 'No_Gain', 'No_Loss', ' United-States', ' <=50K'): 16343, (' White', 'No_Gain', 'No_Loss', ' Private', ' <=50K'): 13634, (' White', 'No_Gain', ' United-States', ' Private', ' <=50K'): 12903, (' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States'): 14133, ('Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' Private'): 15696, ('Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' <=50K'): 16522, ('Reasonable', 'No_Gain', 'No_Loss', ' Private', ' <=50K'): 14288, ('Reasonable', 'No_Gain', ' United-States', ' Private', ' <=50K'): 13133, ('No_Gain', 'No_Loss', ' United-States', ' Private', ' <=50K'): 14514}

C 6 :
 {(' White', ' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States'): 12733, (' White', ' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' Private'): 10115, (' White', ' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' <=50K'): 9923, (' White', ' Male', 'Reasonable', 'No_Gain', ' United-States', ' Private'): 9877, (' White', ' Male', 'Reasonable', 'No_Gain', ' United-States', ' <=50K'): 9454, (' White', ' Male', 'Reasonable', 'No_Loss', ' United-States', ' Private'): 10347, (' White', ' Male', 'Reasonable', 'No_Loss', ' United-States', ' <=50K'): 9578, (' White', ' Male', 'Reasonable', ' United-States', ' Private', ' <=50K'): 7452, (' White', ' Male', 'No_Gain', 'No_Loss', ' United-States', ' Private'): 10193, (' White', ' Male', 'No_Gain', 'No_Loss', ' United-States', ' <=50K'): 10314, (' White', ' Male', 'No_Gain', ' United-States', ' Private', ' <=50K'): 7898, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' Private'): 13729, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' <=50K'): 14140, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' Private', ' <=50K'): 11968, (' White', 'Reasonable', 'No_Gain', ' United-States', ' Private', ' <=50K'): 11289, (' White', 'Reasonable', 'No_Loss', ' United-States', ' Private', ' <=50K'): 11401, (' White', 'No_Gain', 'No_Loss', ' United-States', ' Private', ' <=50K'): 12484, (' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' Private'): 10319, (' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' <=50K'): 10282, (' Male', 'Reasonable', 'No_Gain', ' United-States', ' Private', ' <=50K'): 8023, (' Male', 'No_Gain', 'No_Loss', ' United-States', ' Private', ' <=50K'): 8619, ('Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' Private', ' <=50K'): 12720}


L 6 :
 {(' White', ' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States'): 12733, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' Private'): 13729, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' <=50K'): 14140, (' White', 'No_Gain', 'No_Loss', ' United-States', ' Private', ' <=50K'): 12484, ('Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' Private', ' <=50K'): 12720}


C 7 :
 {(' White', ' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' Private'): 9295, (' White', ' Male', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' <=50K'): 9110, (' White', ' Male', 'Reasonable', 'No_Gain', ' United-States', ' Private', ' <=50K'): 7104, (' White', ' Male', 'No_Gain', 'No_Loss', ' United-States', ' Private', ' <=50K'): 7624, (' White', 'Reasonable', 'No_Gain', 'No_Loss', ' United-States', ' Private', ' <=50K'): 10915}


L 7 :
 {}

Total execution time =  1294.5864036083221